### ISSUE TITLE
Application de Calibration

### ISSUE THREAD

**Issue by feeley** [udem-dlteam/calib-oups#1]
L'application de calibration sera utilisée lors de la fabrication du dynamomètre pour calibrer le senseur de force, l'accéléromètre et le gyroscope. Cette application sera également utilisable par une personne techniquement apte, tel qu'un des membres de l'équipe de recherche ou un intervenant du système de santé pour vérifier le bon fonctionnement du dynamomètre avant son utilisation.

L'application sera utilisable sur ordinateur de bureau et sur appareil mobile, sous forme d'application web.

**Comment by LaboDumoulin** [comment]
testing one two @omelancon

**Comment by feeley** [comment]
@LaboDumoulin bien reçu!

Comme tu vois c'est une façon de discuter sur une tâche, un peu comme des courriels ou un "chat". Ça a comme avantage de centraliser la discussion pour chaque sous-projet et laisser une trace de la discussion. Avec la notation "@--username--" (comme je l'ai fait ci-dessus avec @LaboDumoulin) on peut alerter d'autres personnes pour qu'ils joignent la conversation.

**Comment by leo-ard** [comment]
L'application est faite et elle est fonctionnelle ! Voici le lien pour y accéder : https://udem-dlteam.github.io/calib-oups/
